### ISSUE TITLE
ts-node: Property 'body' does not exist on type 'Request'.

### ISSUE THREAD

**Issue by woldner** [koajs/koa-body#109]
## Problem/Feature Request Summary
There seem to be something wrong with the typings of `koa-body`. You sometimes get unexpected results when used together with ts-node:

```
/Users/m41n/source/repos/koabody/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/controller.ts(5,39): error TS2339: Property 'body' does not exist on type 'Request'.

    at createTSError (/Users/m41n/source/repos/koabody/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/Users/m41n/source/repos/koabody/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/Users/m41n/source/repos/koabody/node_modules/ts-node/src/index.ts:557:11)
    at Module.m._compile (/Users/m41n/source/repos/koabody/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/m41n/source/repos/koabody/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
[nodemon] app crashed - waiting for file changes before starting...
```

## Environment Information

  * `koa-body: 4.0.4`
  * `koa: 2.5.2`
  * `node: 10.6.0`

## Steps to Reproduce

reproducible repo:
https://github.com/jwldnr/koabody

* install dependencies using yarn  
-> `cd koabody && yarn`

* start nodemon  
-> `yarn serve`

.. initial compile is ok (?). (no errors)  
* open `src/controller.ts` and edit the `console.log` line while nodemon is running

e.g. `console.log("initial", email)`  
-> `console.log("changed", email)`

Error:  
`TSError: ⨯ Unable to compile TypeScript:
src/controller.ts(5,39): error TS2339: Property 'body' does not exist on type 'Request'.`

**Comment by MarkHerhold** [comment]
Thank you for the example repo! I'll look at it this evening.

**Comment by doveccl** [comment]
I think its the defect of ts-node, similar problem occurs to me.
For the same project:
- run `tsc` will compile without error
- run `ts-node` will get: error TS2459: Type 'Request' has no property 'body' and no string index signature

I tried to add additional config to `tsconfig.json`, and then the error disappeared:
```
{
	"compilerOptions": {
		"typeRoots": [
			"./node_modules/@types",
			"./node_modules/koa-body"
		],
		// ...
	}
}
```

It is because `tsc` could find from `node_modules/koa-body/index.d.ts`, but `ts-node` can't.
`ts-node` will only search `d.ts` files under `node_modules/@types`.

@MarkHerhold I think you can move `index.d.ts` to `@types/koa-body`

**Comment by mariotacke** [comment]
Getting the same error. I had to put koa-body before @types in my tsconfig typeRoots and it works.

```
{
  "compilerOptions": {
    "typeRoots": [
      "node_modules/@types",
      "node_modules/koa-body",
      "src/typings"
    ]
  },
}

```

Does not work.

```
{
  "compilerOptions": {
    "typeRoots": [
      "node_modules/koa-body",
      "node_modules/@types",
      "src/typings"
    ]
  },
}
```

Works.

Weird. I also have koa-router typings installed, I have a feeling they override the koa typings somehow...

**Comment by nerdDan** [comment]
@mariotacke same here

**Comment by dab00** [comment]
adding /// <reference path='path_to_root_folder/node_modules/koa-body/index.d.ts' /> helps

**Comment by winverse** [comment]
ts-node -v6 it is work!

**Comment by lucifer1004** [comment]
Explicitly import koaBody can solve this problem.

```javascript
import koaBody from 'koa-body';
```

**Comment by Triment** [comment]
> adding `/// <reference path='path_to_root_folder/node_modules/koa-body/index.d.ts' />` helps

great ! its working for me

**Comment by UncleYee** [comment]
I tried to configure tsconfig.json as follows, and the problem was solved
```
{
  "compilerOptions": {
    "typeRoots": [
      "node_modules/**/*",
    ]
  },
}
```

**Comment by UncleYee** [comment]
```
{
  "compilerOptions": {
    "types": [
      "koa-body",
    ]
  },
}

```

**Comment by jpolair** [comment]
I think you don't have to change the tsCongig file, you just have to install the definition types as dev depedencies. 
`"devDependencies": {
    "@babel/core": "^7.8.3",
    "@babel/preset-env": "^7.8.3",
    "@babel/preset-typescript": "^7.8.3",
    "@types/jest": "^24.9.0",
    "@types/koa": "^2.11.0",
    "@types/koa-bodyparser": "^4.3.0",
    "@types/koa-json": "^2.0.18",
    "@types/koa-logger": "^3.1.1",
    "@types/koa-router": "^7.4.0",
    "@types/node": "^13.1.8",
    "babel-jest": "^24.9.0",
    "jest": "^24.9.0",
    "nodemon": "^2.0.2",
    "ts-node": "^8.6.2",
    "typescript": "^3.7.5"
  }`

**Comment by MarkHerhold** [comment]
#213 re-implements this project in TS
