### ISSUE TITLE
Typescript definitions incompatible with `@types/koa@2.0.49`

### ISSUE THREAD

**Issue by esetnik** [koajs/koa-body#155]
## Problem/Feature Request Summary

Typescript definitions incompatible with `@types/koa@2.0.49`

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36016

## Environment Information

  * koa-body: v4.1.0
  * Koa: v2.7.0
  * Node.js: v10.16.0

## Current Behavior

`Property 'body' does not exist on type 'Request'.`

## Steps to Reproduce
```js
// request
app.use(ctx => {
    const body = ctx.request.body;
});
```

## Expected Behavior
No typescript error

**Comment by damianb** [comment]
Suspect this is something very much like DefinitelyTyped/DefinitelyTyped#22568.

**Comment by MarkHerhold** [comment]
Adding TS test for the project here in https://github.com/dlau/koa-body/pull/177

**Comment by 1eejay** [comment]
maybe you should define the middleware Type
import { MiddleWare } from '@koa/router'
type **Middleware** from @koa/router or koa

` // xxx.ts
const controller: Middleware = async (ctx) => {
    const body = ctx.request.body
}
app.use(controller)
`

**Comment by MarkHerhold** [comment]
#213 should address this
