### ISSUE TITLE
Move to KoaJS org?

### ISSUE THREAD

**Issue by jonathanong-houzz** [koajs/koa-body#187]
this is a great module. want to move it to the koajs github org so that it could have more maintainers and seem more official? let me know

- Jon

**Comment by inca** [comment]
Sorry for +1-esque comment, but I'd really like that. Even the fact that there are no replies for a couple of months makes the module seem a bit untrustworthy.

**Comment by MarkHerhold** [comment]
@jonathanong-houzz @inca  I'm the maintainer now (admittedly need to spend more time here) whereas @dlau  is the owner. I don't have the permissions to move this into the koa org but I would be in total support of it.

**Comment by dlau** [comment]
@MarkHerhold  thanks for pinging me. Would love to help transfer it over.

I don't have permissions to create repositories in the koajs org, what's the general process here? @jonathanong-houzz 

<img width="845" alt="Screen Shot 2021-05-14 at 9 37 59 AM" src="https://user-images.githubusercontent.com/2764274/118301760-4a544f00-b498-11eb-9fff-d77a9bd21df5.png">

**Comment by jonathanong** [comment]
@dlau transfer to me @jonathanong and I'll transfer to koa and add you all as collaborators. you have to be an owner of the org to transfer.

mind the username - I accidentally commented with my work GitHub account above 😂

**Comment by dlau** [comment]
@jonathanong  got it. I've initiated the transfer, please let me know if I can help in any way.

**Comment by jonathanong** [comment]
done!

**Comment by jonathanong** [comment]
@dlau @MarkHerhold also invited you to the org, please accept

**Comment by MarkHerhold** [comment]
@jonathanong accepted, thanks!

**Comment by MarkHerhold** [comment]
@dlau did you add members of the koa team to npm for publishing or transfer ownership?
@jonathanong (assuming answer is no) who should those people/that team be?

**Comment by dlau** [comment]
@MarkHerhold Thanks for following up. I did not update any npm permissions yet
@jonathanong let us know who to add

thanks again everyone for your help, I think this module will do great under the koajs org's stewardship :-)
