### ISSUE TITLE
With "hashalgorithm: MD5" set, how to get the MD5 value of a file in "onfilebegin"?

### ISSUE THREAD

**Issue by sunmr1987** [koajs/koa-body#208]
## Describe the feature

The result I got with "file.hash" is
`Hash {
    _options: undefined,
    [Symbol(kHandle)]: Hash {},
    [Symbol(kState)]: { [Symbol(kFinalized)]: false }
  }`
How do I turn it into a string?

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.

**Comment by MarkHerhold** [comment]
Not sure! This option gets passed to formidable https://github.com/node-formidable/formidable#options
