### ISSUE TITLE
[feat] New major version release

### ISSUE THREAD

**Issue by TheDadi** [koajs/koa-body#214]
## Describe the feature
- bump version to 6.0 since we removed the strict option
- release new package version on npm

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.

**Comment by TheDadi** [comment]
@MarkHerhold could you please take care to release the package on npm. Now the code released on npm and here on github are diverging. Thx 📦

**Comment by MarkHerhold** [comment]
@TheDadi  published as v6
Thanks for all your hard work!
