### ISSUE TITLE
formidable 2.0.1 has some wrong

### ISSUE THREAD

**Issue by RookieGz** [koajs/koa-body#224]
## Describe the bug

![截屏2023-01-05 14 59 40](https://user-images.githubusercontent.com/45303288/210720770-7a410443-8e4a-4d2a-8e6b-2f3345dbd451.png)

**Node.js version:** v16.19.0

**OS version:** macOS Ventura 13.1

**Description:**

i try to package a nodejs app with webpack5, but when the app running has a error: 
```javascript
hexoid is not a function
```
I notice has a `formidable 2.0.1`, Maybe it's a bug with this package

[formidable 2.0.1](https://github.com/node-formidable/formidable/issues/871)

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.
- [x] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by wxfred** [comment]
Any solution, pls?

**Comment by RookieGz** [comment]
@wxfred  add this code in webpack.config.js
` plugins: [
    new NormalModuleReplacementPlugin(
      /^hexoid$/,
      require.resolve("hexoid/dist/index.js")
    ),
  ],`

**Comment by wxfred** [comment]
> @wxfred add this code in webpack.config.js ` plugins: [ new NormalModuleReplacementPlugin( /^hexoid$/, require.resolve("hexoid/dist/index.js") ), ],`

Not work for me, but really helpful to locate the problem -- webpack5 uses hexoid/dist/index.mjs by default while formidable uses it as a CommonJS module. I'm using `vue-cli-plugin-electron-builder`, finally, i found a work around
in vue.config.js
```
module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess(config) {
        config.resolve.alias
          .set('hexoid', 'hexoid/dist/index.js')
```

Thanks a lot.
